name: Go Build and Deploy for dev
on:
  pull_request:
    paths:
      - "src/golang-example/**"
    types:
      - closed
jobs:
  deploy:
    if: github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'develop'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.23.x"
      - name: Build and Zip
        run: |
          go build bootstrap.go
          zip bootstrap.zip bootstrap
        working-directory: src/golang-example
      - name: Deploy
        env:
          AWS_ACCESS_KEY_ID: ${{ vars.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ap-northeast-1
        run: |
          aws lambda update-function-code --function-name golang-example --zip-file fileb://bootstrap.zip
        working-directory: src/golang-example
