name: Go Test
on:
  pull_request:
    paths:
      - 'src/golang-example/**'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23.x'
      - name: Test
        run: go test -v
        working-directory: src/golang-example
