name: Python Build and Deploy for dev
on:
  pull_request:
    paths:
      - "src/python-example/**"
    types:
      - closed
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Display Python version
        run: python -c "import sys; print(sys.version)"

      - name: Install uv
        uses: astral-sh/setup-uv@v4

      - name: Install the project
        run: uv sync --all-extras --dev
        working-directory: src/python-example

      - name: Zip Layer
        run: |
          mkdir ./python
          cp -fr .venv/lib ./python/
          zip -r layer_content.zip ./python
        working-directory: src/python-example

      - name: Zip Code
        run: zip lambda_function.zip ./lambda_function.py
        working-directory: src/python-example

      - name: Publish new layer version
        env:
          AWS_ACCESS_KEY_ID: ${{ vars.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ap-northeast-1
        run: |
          NEW_LAYER_VERSION=$(aws lambda publish-layer-version \
            --layer-name python-example \
            --zip-file fileb://layer_content.zip \
            --query "LayerVersionArn" \
            --output text \
          )
          echo "NEW_LAYER_VERSION=${NEW_LAYER_VERSION}" >> $GITHUB_ENV
          cat $GITHUB_ENV
        working-directory: src/python-example

      - name: Update function code
        env:
          AWS_ACCESS_KEY_ID: ${{ vars.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ap-northeast-1
        run: |
          aws lambda update-function-configuration --function-name python-example --layers ${{ env.NEW_LAYER_VERSION }}
          aws lambda update-function-code --function-name python-example --zip-file fileb://lambda_function.zip
        working-directory: src/python-example
